<?php

namespace Louvre\TicketingBundle\Repository;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends \Doctrine\ORM\EntityRepository
{
    public function myCount($dateVisit, $count){
        $qb = $this->createQueryBuilder('p')
            ->select('sum(p.nbrTickets)')
            ->where('p.dateVisit = :dateVisit')
            ->setParameter('dateVisit', $dateVisit)
            ->getQuery();
        $nbrTicket = $qb->getSingleScalarResult();
        if ((int)$nbrTicket + $count >= 1000) {
            return false;
        } else {
            return true;
        }
    }
}
