louvre_ticketing_homepage:
    path:     /
    defaults: { _controller: LouvreTicketingBundle:Ticketing:index }

louvre_ticketing_validation:
    path:    /validation/{id}
    defaults: { _controller: LouvreTicketingBundle:Ticketing:validation }
    requirements:
        id:  \d+
