services:
    louvre_ticketing.tickets:
        class: Louvre\TicketingBundle\Services\Tickets

    louvre_ticketing.mailer:
        class: Louvre\TicketingBundle\Services\SwiftMailer
        arguments:
            - "@twig"
            - "@mailer"


